package com.example.MyBookShopApp.dto;

import com.example.MyBookShopApp.dto.relationship.Book2Author;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@ApiModel(description = "data model of author entity")
@Entity
@Table(name = "authors")
public class Author {

    @ApiModelProperty(value = "author id generated by db", position = 1)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @ApiModelProperty(value = "photo of author", position = 2)
    private String photo;
    @ApiModelProperty(value = "slug by author", position = 3)
    @NotNull
    private String slug;
    @ApiModelProperty(value = "name by author", example = "Steven King", position = 4)
    @NotNull
    private String name;
    @ApiModelProperty(value = "description by author", position = 5)
    @Column(columnDefinition = "text")
    private String description;

    @OneToMany(mappedBy = "author")
    @JsonIgnore
    private List<Book2Author> book2Authors = new ArrayList<>();

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return "Author{" +
                "id=" + id +
                ", photo='" + photo + '\'' +
                ", slug='" + slug + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}
